import "@azure-tools/typespec-azure-core";
import "@azure-tools/typespec-azure-resource-manager";
import "@typespec/openapi";
import "@typespec/rest";
import "./models.tsp";
import "./WebPubSubResource.tsp";

using TypeSpec.Rest;
using Azure.ResourceManager;
using TypeSpec.Http;
using TypeSpec.OpenAPI;

namespace Microsoft.SignalRService;
/**
 * A class represent a replica resource.
 */
@parentResource(WebPubSubResource)
model Replica is Azure.ResourceManager.TrackedResource<ReplicaProperties> {
  ...ResourceNameParameter<
    Resource = Replica,
    KeyName = "replicaName",
    SegmentName = "replicas",
    NamePattern = "^[a-zA-Z][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]$"
  >;

  /**
   * The billing information of the resource.
   */
  sku?: ResourceSku;
}

@armResourceOperations
interface Replicas {
  /**
   * Get the replica and its properties.
   */
  @operationId("WebPubSubReplicas_Get")
  get is ArmResourceRead<Replica>;

  /**
   * Create or update a replica.
   */
  @operationId("WebPubSubReplicas_CreateOrUpdate")
  createOrUpdate is ArmResourceCreateOrReplaceAsync<Replica>;

  /**
   * Operation to update an exiting replica.
   */
  @operationId("WebPubSubReplicas_Update")
  @patch(#{ implicitOptionality: false })
  update is ArmCustomPatchAsync<
    Replica,
    PatchModel = Replica,
    Response = ArmResourceUpdatedResponse<Replica>
  >;

  /**
   * Operation to delete a replica.
   */
  @operationId("WebPubSubReplicas_Delete")
  delete is ArmResourceDeleteSync<Replica>;

  /**
   * List all replicas belong to this resource
   */
  @operationId("WebPubSubReplicas_List")
  list is ArmResourceListByParent<Replica, Response = ArmResponse<ReplicaList>>;

  /**
   * List all available skus of the replica resource.
   */
  @operationId("WebPubSub_ListReplicaSkus")
  @get
  @action("skus")
  listReplicaSkus is ArmResourceActionSync<Replica, void, ArmResponse<SkuList>>;

  /**
   * Operation to restart a replica.
   */
  @operationId("WebPubSubReplicas_Restart")
  restart is ArmResourceActionAsync<Replica, void, NoContentResponse>;
}

@@maxLength(Replica.name, 63);
@@minLength(Replica.name, 3);
@@doc(Replica.name, "The name of the replica.");
@@doc(Replica.properties, "");
@@doc(Replicas.createOrUpdate::parameters.resource,
  "Parameters for the create or update operation"
);
@@doc(Replicas.update::parameters.properties,
  "Parameters for the update operation"
);
